# Generated by Django 2.2.7 on 2020-05-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodos_seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glo_periodos_seguimiento',
            name='id_periodo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
