# Generated by Django 2.2.7 on 2020-05-25 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodos_seguimiento', '0002_auto_20200525_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glo_periodos_seguimiento',
            old_name='id_periodo',
            new_name='id_periodo_seguimiento',
        ),
    ]
