# Generated by Django 2.2.7 on 2020-05-26 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodos', '0002_glo_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glo_seguimiento',
            name='id_periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='periodos.Glo_Periodos'),
        ),
    ]
