# Generated by Django 2.2.7 on 2020-05-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodos', '0003_auto_20200526_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glo_seguimiento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glo_seguimiento',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
