# Generated by Django 2.2.7 on 2020-05-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodos', '0005_auto_20200528_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glo_seguimiento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
