# Generated by Django 2.2.7 on 2020-06-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodos', '0006_auto_20200528_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='glo_seguimiento',
            name='fecha_inicio_corte',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glo_seguimiento',
            name='fecha_termino_corte',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
