# Generated by Django 2.2.7 on 2020-06-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodos', '0007_auto_20200610_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glo_seguimiento',
            name='fecha_inicio_corte',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glo_seguimiento',
            name='fecha_termino_corte',
            field=models.DateField(blank=True, null=True),
        ),
    ]
