# Generated by Django 2.2.7 on 2020-07-10 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estado_seguimiento', '0002_remove_glo_estadoseguimiento_estado'),
        ('periodos', '0008_auto_20200610_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glo_validacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_termino', models.DateTimeField(blank=True, null=True)),
                ('id_estado_periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estado_seguimiento.Glo_EstadoSeguimiento')),
                ('id_periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='periodos.Glo_Periodos')),
                ('id_periodo_seguimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='periodos.Glo_Seguimiento')),
            ],
        ),
    ]
