# Generated by Django 2.2.7 on 2020-07-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodos', '0009_glo_validacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='glo_seguimiento',
            name='descripcion_seguimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='glo_validacion',
            name='descripcion_validacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
