# Generated by Django 2.2.7 on 2021-03-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodos', '0010_auto_20200710_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glo_validacion',
            old_name='fecha_termino',
            new_name='fecha_termino_validacion',
        ),
    ]
