# Generated by Django 2.2.7 on 2021-03-29 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodos', '0011_auto_20210329_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glo_validacion',
            old_name='fecha_termino_validacion',
            new_name='fecha_termino',
        ),
    ]
