# Generated by Django 2.2.7 on 2021-03-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodos', '0012_auto_20210329_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glo_validacion',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
