# Generated by Django 2.2.7 on 2021-03-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodos', '0013_auto_20210329_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glo_validacion',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
