# Generated by Django 2.2.7 on 2021-12-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodos', '0015_respaldoperiodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ges_RespaldoPeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pn', models.IntegerField(blank=True, null=True)),
                ('primer_nivel', models.CharField(blank=True, max_length=500, null=True)),
                ('id_sn', models.IntegerField(blank=True, null=True)),
                ('segundo_nivel', models.CharField(blank=True, max_length=500, null=True)),
                ('id_tni', models.IntegerField(blank=True, null=True)),
                ('tercer_nivel', models.CharField(blank=True, max_length=500, null=True)),
                ('id_cn', models.IntegerField(blank=True, null=True)),
                ('cuarto_nivel', models.CharField(blank=True, max_length=500, null=True)),
                ('ejes', models.CharField(blank=True, max_length=500, null=True)),
                ('id_oe', models.IntegerField(blank=True, null=True)),
                ('objetivo_estrategico', models.CharField(blank=True, max_length=500, null=True)),
                ('id_ot', models.IntegerField(blank=True, null=True)),
                ('objetivo_tactico', models.CharField(blank=True, max_length=500, null=True)),
                ('id_tn', models.IntegerField(blank=True, null=True)),
                ('objetivo_tacticotn', models.CharField(blank=True, max_length=500, null=True)),
                ('id_op', models.IntegerField(blank=True, null=True)),
                ('objetivo_operativo', models.CharField(blank=True, max_length=500, null=True)),
                ('id_actividad', models.IntegerField(blank=True, null=True)),
                ('descripcion_actividad', models.CharField(blank=True, max_length=500, null=True)),
                ('horas_actividad', models.IntegerField(blank=True, null=True)),
                ('volumen', models.IntegerField(blank=True, null=True)),
                ('personas_asignadas', models.IntegerField(blank=True, null=True)),
                ('total_horas', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio_actividad', models.DateField(blank=True, null=True)),
                ('fecha_termino_actividad', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('fecha_real_inicio', models.DateField(blank=True, null=True)),
                ('fecha_real_termino', models.DateField(blank=True, null=True)),
                ('fecha_reprogramacion_termino', models.DateField(blank=True, null=True)),
                ('justificacion', models.CharField(blank=True, max_length=2500, null=True)),
                ('validada', models.CharField(blank=True, max_length=50, null=True)),
                ('flag_tmp', models.IntegerField(blank=True, null=True)),
                ('flag_reporta', models.IntegerField(blank=True, null=True)),
                ('descripcion_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_familiacargo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_periodicidad', models.CharField(blank=True, max_length=50, null=True)),
                ('id_gp', models.IntegerField(blank=True, null=True)),
                ('descripcion_periodo', models.CharField(blank=True, max_length=50, null=True)),
                ('anio_periodo', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio_periodo', models.DateField(blank=True, null=True)),
                ('fecha_termino_periodo', models.DateField(blank=True, null=True)),
                ('producto_estadistico', models.CharField(blank=True, max_length=150, null=True)),
                ('flag_finalizada', models.IntegerField(blank=True, null=True)),
                ('jefatura', models.CharField(blank=True, max_length=150, null=True)),
                ('estado_flujo_controlador', models.CharField(blank=True, max_length=150, null=True)),
                ('estado_plan_controlador', models.CharField(blank=True, max_length=150, null=True)),
                ('analista_asignado', models.CharField(blank=True, max_length=150, null=True)),
                ('primera_revision', models.CharField(blank=True, max_length=150, null=True)),
                ('segunda_revision', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
