# Generated by Django 2.2.7 on 2022-01-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodos', '0016_ges_respaldoperiodo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ges_RespaldoPeriodo',
        ),
    ]
