# Generated by Django 2.2.7 on 2020-04-22 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actividades', '0001_initial'),
        ('periodos', '0001_initial'),
        ('controlador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ges_Observaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=3000, null=True)),
                ('id_controlador', models.IntegerField(null=True)),
                ('id_objetivo', models.IntegerField(null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('observado', models.IntegerField(blank=True, null=True)),
                ('id_actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='actividades.Ges_Actividad')),
                ('id_jefe_observa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controlador.Ges_Controlador')),
                ('id_periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='periodos.Glo_Periodos')),
                ('user_observa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
