# Generated by Django 2.2.7 on 2020-04-29 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valida_plan2', '0002_auto_20200427_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ges_observaciones_sr',
            name='id_jefe_observa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jefaturas.Ges_Jefatura'),
        ),
    ]
