# Generated by Django 2.2.7 on 2020-05-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_horas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ges_registro_horas',
            name='fecha_insercion',
            field=models.DateField(auto_now=True),
        ),
    ]
