# Generated by Django 2.2.7 on 2020-05-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_horas', '0002_auto_20200501_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ges_registro_horas',
            name='fecha_insercion',
            field=models.DateField(null=True),
        ),
    ]
