# Generated by Django 2.2.7 on 2020-04-06 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('controlador', '0002_ges_controlador_jefatura_primerarevision'),
        ('periodos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ges_Observaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=2000, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('id_actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='actividades.Ges_Actividad')),
                ('id_jefe_observa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controlador.Ges_Controlador')),
                ('id_periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='periodos.Glo_Periodos')),
            ],
        ),
    ]
