# Generated by Django 2.2.7 on 2020-04-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valida_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ges_observaciones',
            name='observacion',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
