# Generated by Django 2.2.7 on 2020-04-06 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('valida_plan', '0002_auto_20200406_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='ges_observaciones',
            name='user_observa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
