# Generated by Django 2.2.7 on 2020-04-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valida_plan', '0004_auto_20200406_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ges_observaciones',
            old_name='user_observa',
            new_name='id_user',
        ),
    ]
