# Generated by Django 2.2.7 on 2020-04-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valida_plan', '0009_auto_20200406_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='ges_observaciones',
            name='observado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
