# Generated by Django 2.2.7 on 2020-04-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valida_plan', '0010_ges_observaciones_observado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ges_observaciones',
            name='fecha_registro',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
