# Generated by Django 2.2.7 on 2020-03-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estructura', '0001_initial'),
        ('eje', '0001_initial'),
        ('periodos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ges_Objetivo_Estrategico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_objetivo', models.CharField(max_length=400)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('ges_eje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eje.Ges_Ejes')),
                ('ges_primer_nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estructura.Ges_PrimerNivel')),
                ('id_periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='periodos.Glo_Periodos')),
            ],
        ),
        migrations.CreateModel(
            name='Ges_Objetivo_Tactico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_objetivo', models.CharField(max_length=400)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('id_objetivo_estrategico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='objetivos.Ges_Objetivo_Estrategico')),
                ('id_periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='periodos.Glo_Periodos')),
                ('id_segundo_nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estructura.Ges_SegundoNivel')),
            ],
        ),
        migrations.CreateModel(
            name='Ges_Objetivo_TacticoTN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_objetivo', models.CharField(max_length=400)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('id_objetivo_tactico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='objetivos.Ges_Objetivo_Tactico')),
                ('id_periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='periodos.Glo_Periodos')),
                ('id_tercer_nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estructura.Ges_TercerNivel')),
            ],
        ),
        migrations.CreateModel(
            name='Ges_Objetivo_Operativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_objetivo', models.CharField(max_length=400)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('id_cuarto_nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estructura.Ges_CuartoNivel')),
                ('id_objetivo_tacticotn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='objetivos.Ges_Objetivo_TacticoTN')),
                ('id_periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='periodos.Glo_Periodos')),
            ],
        ),
    ]
