# Generated by Django 2.2.7 on 2020-04-09 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='logEventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateTimeField(auto_now=True)),
                ('tipo_evento', models.CharField(blank=True, max_length=500, null=True)),
                ('jefatura_dirigida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jefatura_dirigida', to=settings.AUTH_USER_MODEL)),
                ('usuario_evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_evento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
