# Generated by Django 2.2.7 on 2020-05-25 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado_seguimiento', '0002_remove_glo_estadoseguimiento_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glo_Seguimiento_periodos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('id_estado_seguimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estado_seguimiento.Glo_EstadoSeguimiento')),
                ('id_periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id_periodo', to='estado_seguimiento.Glo_EstadoSeguimiento')),
            ],
        ),
    ]
