# Generated by Django 2.2.7 on 2020-05-25 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glo_seguimiento_periodos',
            name='id_periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='periodos.Glo_Periodos'),
        ),
    ]
