# Generated by Django 2.2.7 on 2020-05-25 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estado_seguimiento', '0002_remove_glo_estadoseguimiento_estado'),
        ('periodos', '0001_initial'),
        ('seguimiento', '0002_auto_20200525_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Glo_Seguimiento_periodos',
            new_name='Glo_Seguimiento',
        ),
    ]
