# Generated by Django 2.2.7 on 2020-07-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado_actividad', '0002_remove_glo_estadoactividad_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='glo_estadoactividad',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
