# Generated by Django 2.2.7 on 2022-01-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado_actividad', '0003_glo_estadoactividad_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='glo_estadoactividad',
            name='descripcion_validada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
