# Generated by Django 2.2.7 on 2020-05-01 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controlador', '0004_auto_20200501_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ges_controlador',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
