# Generated by Django 2.2.7 on 2020-05-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlador', '0005_auto_20200501_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ges_controlador',
            name='fecha_ultima_modificacion',
            field=models.DateField(auto_now=True),
        ),
    ]
