# Generated by Django 2.2.7 on 2020-05-28 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlador', '0008_ges_controlador_id_estado_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ges_controlador',
            name='id_estado_plan',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='estado_plan.Glo_EstadoPlan'),
        ),
    ]
