# Generated by Django 2.2.7 on 2020-11-17 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlador', '0010_auto_20201117_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ges_controlador',
            name='analista_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
