# Generated by Django 2.2.7 on 2020-03-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objetivos', '0001_initial'),
        ('periodos', '0001_initial'),
        ('familia_cargo', '0001_initial'),
        ('controlador', '0001_initial'),
        ('periodicidad', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ges_Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_actividad', models.CharField(max_length=2000)),
                ('horas_actividad', models.CharField(max_length=4)),
                ('volumen', models.CharField(max_length=3)),
                ('personas_asignadas', models.CharField(max_length=3)),
                ('total_horas', models.IntegerField()),
                ('fecha_inicio_actividad', models.DateField()),
                ('fecha_termino_actividad', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField()),
                ('id_controlador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlador.Ges_Controlador')),
                ('id_familia_cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='familia_cargo.Glo_FamiliaCargo')),
                ('id_objetivo_operativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='objetivos.Ges_Objetivo_Operativo')),
                ('id_objetivo_tactico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='objetivos.Ges_Objetivo_Tactico')),
                ('id_objetivo_tacticotn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='objetivos.Ges_Objetivo_TacticoTN')),
                ('id_periodicidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='periodicidad.Glo_Periodicidad')),
                ('id_periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='periodos.Glo_Periodos')),
                ('id_producto_estadistico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.Glo_ProductosEstadisticos')),
            ],
        ),
    ]
