# Generated by Django 2.2.7 on 2020-05-26 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estado_actividad', '0002_remove_glo_estadoactividad_estado'),
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ges_actividad',
            name='id_estado_actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estado_actividad.Glo_EstadoActividad'),
        ),
    ]
