# Generated by Django 2.2.7 on 2020-06-01 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estado_actividad', '0002_remove_glo_estadoactividad_estado'),
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ges_actividad',
            name='fecha_real_termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ges_actividad',
            name='fecha_reprogramacion_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ges_actividad',
            name='fecha_reprogramacion_termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ges_actividad',
            name='id_estado_actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estado_actividad.Glo_EstadoActividad'),
        ),
        migrations.AddField(
            model_name='ges_actividad',
            name='justificacion',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
