# Generated by Django 2.2.7 on 2020-06-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_ges_actividad_id_estado_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ges_actividad',
            name='fecha_real_termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ges_actividad',
            name='fecha_reprogramacion_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ges_actividad',
            name='fecha_reprogramacion_termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ges_actividad',
            name='justificacion',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
