# Generated by Django 2.2.7 on 2020-07-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_auto_20200601_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='ges_actividad',
            name='flag_reporta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
