# Generated by Django 2.2.7 on 2020-07-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_ges_actividad_flag_reporta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ges_actividad',
            name='validada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
