# Generated by Django 2.2.7 on 2020-07-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_auto_20200601_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='ges_actividad',
            name='flag_avance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
