# Generated by Django 2.2.7 on 2020-07-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_ges_actividad_flag_avance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ges_actividad',
            old_name='flag_avance',
            new_name='flag_reporta',
        ),
    ]
