# Generated by Django 2.2.7 on 2020-07-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_auto_20200702_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='ges_actividad',
            name='validada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
