# Generated by Django 2.2.7 on 2020-07-30 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodos', '0010_auto_20200710_1648'),
        ('actividades', '0005_auto_20200724_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='ges_log_reportes',
            name='id_periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='periodos.Glo_Periodos'),
        ),
    ]
