# Generated by Django 2.2.7 on 2020-07-30 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estado_actividad', '0003_glo_estadoactividad_orden'),
        ('periodos', '0010_auto_20200710_1648'),
        ('actividades', '0007_auto_20200730_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ges_log_reportes',
            old_name='fecha_reprogramacion_inicio',
            new_name='fecha_inicio',
        ),
        migrations.RenameField(
            model_name='ges_log_reportes',
            old_name='fecha_reprogramacion_termino',
            new_name='fecha_termino',
        ),
        migrations.RemoveField(
            model_name='ges_log_reportes',
            name='id_periodo',
        ),
        migrations.RemoveField(
            model_name='ges_log_reportes',
            name='justificacion',
        ),
        migrations.CreateModel(
            name='Ges_Actividad_Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('fecha_reprogramacion_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_reprogramacion_termino', models.DateTimeField(blank=True, null=True)),
                ('fecha_real_termino', models.DateTimeField(blank=True, null=True)),
                ('justificacion', models.CharField(blank=True, max_length=2000, null=True)),
                ('id_actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='actividades.Ges_Actividad')),
                ('id_estado_actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estado_actividad.Glo_EstadoActividad')),
                ('id_periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='periodos.Glo_Periodos')),
                ('id_periodo_seguimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='periodos.Glo_Seguimiento')),
            ],
        ),
    ]
