# Generated by Django 2.2.7 on 2020-07-31 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlador', '0009_auto_20200528_1009'),
        ('actividades', '0008_auto_20200730_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='ges_actividad_historia',
            name='id_controlador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controlador.Ges_Controlador'),
        ),
    ]
