# Generated by Django 2.2.7 on 2020-09-23 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0009_ges_actividad_historia_id_controlador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ges_actividad',
            name='id_producto_estadistico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.Glo_ProductosEstadisticos'),
        ),
    ]
