# Generated by Django 2.2.7 on 2021-11-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0011_ges_actividad_flag_tmp'),
    ]

    operations = [




    ]
