# Generated by Django 2.2.7 on 2021-01-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0011_ges_actividad_flag_tmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ges_actividad',
            name='fecha_real_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
