# Generated by Django 2.2.7 on 2021-12-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0012_auto_20211124_1137'),
    ]

    operations = [




    ]
