# Generated by Django 2.2.7 on 2021-12-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0013_auto_20211202_1858'),
    ]

    operations = [


    ]
