# Generated by Django 2.2.7 on 2021-01-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0013_ges_actividad_historia_fecha_real_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ges_actividad_historia',
            name='fecha_real_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
