# Generated by Django 2.2.7 on 2021-03-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0014_auto_20210118_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='ges_actividad',
            name='flag_fri',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
