# Generated by Django 2.2.7 on 2021-03-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0017_ges_actividad_flag_finalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ges_actividad_historia',
            name='validada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
